### ISSUE TITLE
A discrepancy between the paper and the code regarding the deletion strategies

### ISSUE THREAD

**Issue by chenyil6** [yisunlp/DAIL#1]
For the "FIFO" strategy, the paper says "Delete the samples that entered the bank earlier," but the code keeps "the samples that entered the bank earlier."

The same issue appears with the "diverse" strategy. Here’s the code snippet for reference (see attached screenshot).

Can you please clarify this? Thanks.

<img width="1144" alt="image" src="https://github.com/yisunlp/DAIL/assets/87589465/076cf0ba-b51e-42c4-9f7c-20a010ab7229">

**Comment by yisunlp** [comment]
You are correct, thank you for your correction.
We rerun the experiment and found that the results are consistent with those in the paper. We may mix some previous versions of code when submitting the final version. So this does not affect the results in the paper
