### ISSUE TITLE
Open-source the code for the other baselines

### ISSUE THREAD

**Issue by txy77** [yisunlp/DAIL#2]
Could you share the code for the other baselines you compared? I would be grateful if you could make it available. I am looking forward to your reply.

**Comment by yisunlp** [comment]
The baselines is already included in our code, encompassing zero-shot, few-shot, and SelfICL. CoT were implemented in the SelfICL repository (https://github.com/ntunlplab/Self-ICL).

**Comment by txy77** [comment]
I'm very sorry to bother you, but we couldn't find all the baselines, including zero-shot, few-shot, and SelfICL in your code. Could you kindly point out where the baseline code is located in your repository?

**Comment by yisunlp** [comment]
For mmlu, https://github.com/yisunlp/DAIL/blob/main/MMLU/Inferencers.py.
For bbh, the results of zero-shot and SelfICL is copied from https://arxiv.org/pdf/2305.15035. For the results not included, we reproduce it with the script in https://github.com/ntunlplab/Self-ICL.

**Comment by txy77** [comment]
Thank you very much for your patient reply. Best Wishes!

**Comment by yisunlp** [comment]
In https://arxiv.org/pdf/2305.15035, they reported the results of zero-shot and SelfICL with gpt-3.5-turbo-instruct, we reproduce the result of it with few-shot and CoT.
For gpt-4-1106-preview, you may need to make some brief modifications to his code repository, mainly in the logic of obtaining responses. Sometimes gpt-4-1106-preview may have some content reviews that prevent it from returning. We have a simple demo that you can refer to for reference, which we use it to get the response of gpt-4-1106-preview in our experiment.

**Comment by yisunlp** [comment]
def get_response_from_api(params, query):
    if "gpt-4" in params["model"]:
        response = None
        while response is None:
            try:
                response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while not response.choices and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].message.content
    else:
        response = None
        while response is None:
            try:
                response = openai.Completion.create(prompt=query, **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while ("choices" not in response.keys() or not response.choices) and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.Completion.create(prompt=query, **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].text.strip()

**Comment by yisunlp** [comment]
`def get_response_from_api(params, query):
    if "gpt-4" in params["model"]:
        response = None
        while response is None:
            try:
                response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while not response.choices and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].message.content
    else:
        response = None
        while response is None:
            try:
                response = openai.Completion.create(prompt=query, **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while ("choices" not in response.keys() or not response.choices) and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.Completion.create(prompt=query, **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].text.strip()`

**Comment by yisunlp** [comment]
def get_response_from_api(params, query):
    if "gpt-4" in params["model"]:
        response = None
        while response is None:
            try:
                response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while not response.choices and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.ChatCompletion.create(messages=[{"role": "user", "content": query}], **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].message.content
    else:
        response = None
        while response is None:
            try:
                response = openai.Completion.create(prompt=query, **params)
            except:
                time.sleep(10)
                print("get response failed")
        trying = 0
        while ("choices" not in response.keys() or not response.choices) and trying < 5:
            trying += 1
            print("failed to get content, retrying {}".format(trying))
            time.sleep(60)
            response = openai.Completion.create(prompt=query, **params)
        if trying >= 5:
            return False, "No Result"
        return True, response.choices[0].text.strip()
